name: Build and Deploy Vite App to Hostinger via FTP

on:
  push:
    branches:
      - main  # Change to your branch name if not using "main"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Vite Project
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp://46.202.138.149
          username: u859492031
          password: Xajh@1314
          server-dir: ${{ secrets.FTP_TARGET }}
          local-dir: ./dist/

          
      - name: Enable debug logs
        run: echo "debug=true" >> $GITHUB_ENV
   


